# Generated by Django 4.0.3 on 2022-06-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrep',
            name='salesmade',
        ),
        migrations.AddField(
            model_name='salesrep',
            name='salesmade',
            field=models.ManyToManyField(blank=True, null=True, to='sales_rest.salerecord'),
        ),
    ]
