# Generated by Django 4.0.3 on 2022-06-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_salesrep_salesmade_salesrep_salesmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobileinventoryvo',
            name='manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='automobileinventoryvo',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='automobileinventoryvo',
            name='vehicle_vin',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
