# Generated by Django 4.0.3 on 2022-06-18 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobileinventoryvo_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BOOGIE', to='sales_rest.customer'),
        ),
    ]
