# Generated by Django 4.0.3 on 2022-06-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_salerecord_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobileinventoryvo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='salesmade',
            field=models.ManyToManyField(blank=True, to='sales_rest.salerecord'),
        ),
    ]
