# Generated by Django 4.0.3 on 2022-06-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_automobileinventoryvo_sold_alter_salesrep_salesmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobileinventoryvo',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='automobileinventoryvo',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
