# Generated by Django 4.0.3 on 2022-06-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vin',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='vins',
            field=models.CharField(max_length=100),
        ),
    ]
