# Generated by Django 4.0.3 on 2022-06-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_appointment_vin_alter_automobilevo_vins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vip',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='vip',
            field=models.BooleanField(default=True),
        ),
    ]
