# Generated by Django 4.0.3 on 2022-06-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_remove_appointment_vip_automobilevo_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
